Lab7
Katalien/dx11 pull request #7
Opened 2024-04-01 20:24 UTC by Katalien

2024-04-05 19:18 UTC, maloxit requested changes
Есть ошибки:
- У вас кубы всегда черные, вне зависимости от того сколько и куда источников света ставить
- Фрустум куллинг работает неправильно, кубы ещё на экране, но уже прячутся
- Надо добавить перемещение камеры, чтобы была возможность оценить работу куллинга
- Предупреждения в debug layer
- Максимальную яркость света надо поднять выше единицы

2024-04-07 14:08 UTC, Katalien commented
зум камеры происходит путем нажатия на стрелки вверх-вниз и одновременным движением курсора.
Поясните, пожалуйста, этот момент: "кубы ещё на экране, но уже прячутся". Как это проверить, отследить?

2024-04-07 19:44 UTC, maloxit commented
> зум камеры происходит путем нажатия на стрелки вверх-вниз и одновременным движением курсора. Поворот камеры был реализован до этого. Поясните, пожалуйста, этот момент: "кубы ещё на экране, но уже прячутся". Как это проверить, отследить?


https://github.com/Katalien/dx11/assets/61049974/6d0cdf1c-1bda-4500-b484-b3d6b0a8cf91

2024-04-08 10:45 UTC, Katalien commented
поменяла код frustum

2024-04-08 17:48 UTC, maloxit requested changes
По верхней и нижней плоскости исправилось, по боковым всё ещё проблемы

2024-04-08 18:50 UTC, Katalien commented
Перепроверила. Вроде бы сейчас работает корректно

2024-04-11 14:23 UTC, maloxit approved these changes
Забыли Rendering.h обновить, но в остальном зачёт с плюсом)

2024-04-11 14:24 UTC, maloxit commented
Постпроцессинг тоже зачел

2024-04-12 08:47 UTC, Katalien commented
Исправила, спасибо.

2024-04-12 08:47 UTC, merged